<Widgetx>:
    TextInput:
        id: input_board
        multiline: True
        text: root.board_var
        size: 350,250
        pos: 25,125
        font_size: 20
    TextInput:
        id: user_input
        size: 300,50
        text: "Hi"
        pos: 24,60
        font_size: 20
    Button:
        id: sender
        size: 55,53
        on_press: root.get_inputer()
        text: "Send"
        pos: 320,58
        font_size: 10
   